// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzffeeitqykcewprtbee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZmZlZWl0cXlrY2V3cHJ0YmVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1Mzk4NzIsImV4cCI6MjA3MzExNTg3Mn0.5lZt5HoRFe3T1UcLg9Co32q9zjicGTC6YApbp9FNVl4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});